# Generated by Django 4.0.5 on 2023-05-17 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0009_profile_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='subscription_date',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
