# Generated by Django 4.0.5 on 2023-06-04 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0011_ticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='answer',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='has_read',
            field=models.BooleanField(default=False),
        ),
    ]
