name: Release

on:
  workflow_run:
    workflows: [ CI ]
    branches: [ main ]
    types:
      - completed


jobs:
  build:
    runs-on: ubuntu-latest

    env:
      GITHUB_TOKEN: ${{ secrets.PAT }}

    steps:
    - uses: actions/checkout@v2

    - id: release
      uses: rymndhng/release-on-push-action@master
      with:
          bump_version_scheme: minor

    - name: Tag image
      run: |
        docker login --username=${{ secrets.REGISTRY_USERNAME }} --password=${{ secrets.PAT }} ghcr.io
        export TAG=${{ github.sha }}
        echo $TAG
        docker pull ghcr.io/mehdi-mostafavi/saku:$TAG
        docker tag ghcr.io/mehdi-mostafavi/saku:$TAG ghcr.io/mehdi-mostafavi/saku:${{ steps.release.outputs.tag_name }}
        docker push ghcr.io/mehdi-mostafavi/saku:${{ steps.release.outputs.tag_name }}

    - name: Tag Latest
      run: |
        docker login --username=${{ secrets.REGISTRY_USERNAME }} --password=${{ secrets.PAT }} ghcr.io
        export TAG=${{ github.sha }}
        echo $TAG
        docker pull ghcr.io/mehdi-mostafavi/saku:$TAG
        docker tag ghcr.io/mehdi-mostafavi/saku:$TAG ghcr.io/mehdi-mostafavi/saku:latest
        docker push ghcr.io/mehdi-mostafavi/saku:latest