name: Staging

on:
  workflow_run:
    workflows: [ CI ]
    branches: [ develop ]
    types:
      - completed

jobs:

  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: webfactory/ssh-agent@v0.5.4
        with:
            ssh-private-key: ${{ secrets.SSH }}

      - name: Deploy
        shell: bash
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@188.121.110.151 "cd Saku-Backend && export TAG=${{ github.sha }} &&  docker-compose -f docker-compose.staging.yml down && docker-compose -f docker-compose.staging.yml up -d"