# Generated by Django 4.0.5 on 2023-04-16 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0010_remove_auction_tags_auction_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='mode',
            field=models.IntegerField(choices=[(1, 'Increasing'), (2, 'Decreasing')], default=(1, 'Increasing')),
        ),
    ]
