# Generated by Django 4.0.5 on 2023-04-18 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0011_alter_auction_mode_score'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='score',
            constraint=models.UniqueConstraint(fields=('auction', 'user'), name='score_pk'),
        ),
    ]
