# Generated by Django 4.0.5 on 2023-04-22 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0011_alter_auction_mode'),
        ('auction', '0012_score_score_pk'),
    ]

    operations = [
    ]
