# Generated by Django 4.0.5 on 2023-05-05 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0015_alter_auction_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='auction.city'),
        ),
    ]
