# Generated by Django 4.0.5 on 2023-05-17 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscription',
            old_name='duration',
            new_name='usage_limit',
        ),
    ]
