name: CD

on:
  # release:
  #   types:
  #     - created
  workflow_run:
    workflows: [image-release]
    branches: [main]
    types:
      - completed

jobs:

  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: webfactory/ssh-agent@v0.5.4
        with:
            ssh-private-key: ${{ secrets.SSH }}

      # - name: Set env
      #   run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Deploy
        shell: bash
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@188.121.97.132 "cd Saku-Backend && docker-compose -f docker-compose.deploy.yml pull --ignore-pull-failures && docker-compose -f docker-compose.deploy.yml up -d"
