name: dev-test

on:
  push:
    branches: [develop, master]
  pull_request:
    branches: [develop, master]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Run Tests
      run: |
        docker-compose -f docker-compose.dev-test.yml run web

